Bot funcionality
ZwergB/stupidbot pull request #2
Opened 2020-11-26 23:50 UTC by Til7701

sorry

2020-11-27 00:46 UTC, ZwergB requested changes
gut

2020-11-27 00:46 UTC, ZwergB commented on DiscordBot.js
> +            let prefix = "$";
Sollte global beim constructor festgelegt werden

2020-11-27 00:46 UTC, ZwergB commented on DiscordBot.js
> +            const coursesFile       = JSON.parse(fs.readFileSync(coursesFilePath));
Warum werden diese immer geladen, auch wenn sie nicht genutzt werden? Nur wenn die Dateien auch wirklich gelesen oder beschrieben werden, sollten sie auch geladen werden

2020-11-27 00:46 UTC, ZwergB commented on DiscordBot.js
> +            let respondContent = "";
Warum steht das hier? Kann weg oder?

2020-11-27 00:46 UTC, ZwergB commented on DiscordBot.js
> +                let args = msg.content.split(" "); //split in arguments
Das sollte erst da gesplittet werden, so es wirklich gebraucht wird. Außerdem ist es später etwas unersichtlich wo dieses args her kommt und was es genau aussagt wenn es hier initialisiert wird.

2020-11-27 00:46 UTC, ZwergB commented on DiscordBot.js
> +                                    "§resend filename"
Dies kann in eine seperate .json ausgelagert werden, da der Inhalt (bzw. Text) komplett statisch ist. Außerdem sollte das präfix dynamisch hinzugefügt werden falls es sich ändert.

2020-11-27 00:46 UTC, ZwergB commented on DiscordBot.js
> +                    case msg.content.startsWith(prefix + "addChannel ") || msg.content.startsWith(prefix + "ach "):
Finde ich in diesem Zustand zu gefährlich, keine Fehlerabfangung oder Eingabeüberprüfung macht ein extremes Sicherheitsrisiko. Erstmal sperren, solange das nicht gewehrleistet ist.

2020-11-27 00:46 UTC, ZwergB commented on DiscordBot.js
> +                    case msg.content.startsWith(prefix + "rmChannel ") || msg.content.startsWith(prefix + "rmch "):
Das Gleiche wie add

2020-11-27 00:46 UTC, ZwergB commented on DiscordBot.js
> +                    case msg.content.startsWith(prefix + "editChannel ") || msg.content.startsWith(prefix + "ech "):
Das gleiche wie add

2020-11-27 00:46 UTC, ZwergB commented on DiscordBot.js
> +                    case msg.content.startsWith(prefix + "addCourse ") || msg.content.startsWith(prefix + "aco "):
Gleiche wie add channel

2020-11-27 00:46 UTC, ZwergB commented on DiscordBot.js
> +                    case msg.content.startsWith(prefix + "rmCourse ") || msg.content.startsWith(prefix + "rmco "):
Gleiche wie add channel

2020-11-27 00:46 UTC, ZwergB commented on DiscordBot.js
> +                    case msg.content.startsWith(prefix + "editCourse ") || msg.content.startsWith(prefix + "eco "):
Gleiche wie add channel

2020-11-27 00:46 UTC, ZwergB commented on DiscordBot.js
>                  switch(true) {
Dieser gesamte switch Ausdruck sollte in eine config json ausgelagert werden und ihre einzelnen cases in functions ausgelagert werden. Das würde dem ganzen mehr dynamische und allgemein durchsichte Struktur geben.

2020-11-27 03:00 UTC, Til7701 commented
das wären erstmal die Änderungen.... muss ich die pull request neu machen, oder siehst du das hier?

2020-11-27 20:42 UTC, ZwergB requested changes
gut.2

2020-11-27 20:42 UTC, ZwergB commented on CommandFunctions.js
> +const Discord = require('discord.js');
Brauchen wir das require hier? Glaube net.

2020-11-27 20:42 UTC, ZwergB commented on CommandFunctions.js
> +        const respond = [[], [], []];
respondContent, so wie die anderen

2020-11-27 20:42 UTC, ZwergB commented on config/commands.json
> +        "shortcut": "none",
Glaube none ist hier etwas ungünstig, wenn man prefix + "none" eingibt, wird der command ausgeführt. Lieber leer lassen (oder null oder so) und im code abfangen, falls diese Eigenschaft leer ist.

2020-11-27 20:42 UTC, ZwergB commented on config/commands.json
> +        "shortcut": "none",
-> r

2020-11-27 20:42 UTC, ZwergB commented on CommandFunctions.js
> +        respondContent[1][0] = channel.id;
Aufpassen, wenn channel oder course nicht gefunden wird, stürzt das hier hart ab. Das sollte abgefangen werden.

2020-11-27 20:42 UTC, ZwergB commented on config/commands.json
> +        "command": "addCourse",
Nicht benutzbare command entweder markieren oder rausnehmen

2020-11-27 21:59 UTC, ZwergB commented on DiscordBot.js
> +const { connect } = require('http2');
?

2020-11-29 21:32 UTC, ZwergB approved these changes

2020-11-29 21:50 UTC, merged